# Generated by Django 4.2.3 on 2023-07-31 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drawing',
            old_name='tagged_kid',
            new_name='kid_owner_drawing',
        ),
    ]
