# Generated by Django 4.2.3 on 2023-08-05 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0004_alter_drawing_kid_owner_drawing'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='to_drawing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawings.drawing'),
        ),
    ]
