# Generated by Django 4.2.3 on 2023-08-11 18:51

import FINAL_EXAM.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0003_alter_kid_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='name',
            field=models.CharField(max_length=30, validators=[FINAL_EXAM.validators.only_letters_validator]),
        ),
    ]
