# Generated by Django 4.2.3 on 2023-07-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='is_kid',
            new_name='is_visitor',
        ),
    ]
