# Generated by Django 4.2.3 on 2023-08-11 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_appuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Ensure username has at least 2 characters (it has 1).')]),
        ),
    ]
