# Generated by Django 4.2.3 on 2023-08-11 18:51

import FINAL_EXAM.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_appuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Ensure first name has at least 2 characters (it has 1).'), FINAL_EXAM.validators.only_letters_validator]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Ensure last name has at least 2 characters (it has 1).'), FINAL_EXAM.validators.only_letters_validator]),
        ),
    ]
